services:
  - type: web
    name: abct-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: coronadonoell@gmai.com
        sync: false
      - key: xxxxxxbxeysvebn
        sync: false